---
AssignmentInConditionalCheck:
CaseMissingElseCheck:
ClassLineCountCheck:
  line_count: 200
ClassNameCheck:
  pattern: !ruby/regexp /^[A-Z][a-zA-Z0-9]*$/
ClassVariableCheck:
CyclomaticComplexityBlockCheck:
  complexity: 3
CyclomaticComplexityMethodCheck:
  complexity: 5
EmptyRescueBodyCheck:
ForLoopCheck:
MethodLineCountCheck:
  line_count: 6
MethodNameCheck:
  pattern: !ruby/regexp /^[\||\^|\&|\!]$|^[_a-z<>=\[|+-\/\*`]+[_a-z0-9_<>=~@\[\]]*[=!\?]?$/
ModuleLineCountCheck:
  line_count: 200
ModuleNameCheck:
  pattern: !ruby/regexp /^[A-Z][a-zA-Z0-9]*$/
ParameterNumberCheck:
  parameter_count: 5
